name: Build and Deploy to AWS ECR

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout app repository
      uses: actions/checkout@v2

    - name: Checkout manifest repository
      uses: actions/checkout@v2
      with:
        repository: 0jaepark/manifest
        path: manifest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ap-northeast-2
        role-to-assume: ${{ secrets.ARN_ECR_PUSH_ROLE }}
        role-session-name: ecrPrivatePushRole

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: private

    - name: Set image tag
      id: set-var
      run: |
        echo "ECR_REGISTRY=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV
        echo "ECR_REPOSITORY=my-app-repo" >> $GITHUB_ENV
        echo "IMAGE_TAG=$(echo ${GITHUB_SHA:0:7})" >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build \
          -f Dockerfile \
          -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .

    - name: Push Docker image to ECR
      run: |
        docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

    - name: Update Kubernetes manifest with new image
      run: |
        cd manifest
        sed -i "s|image:.*|image: ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}|" k8s/deploy-basic.yml
